name: Build and Share AMI

on:
  push:
    branches:
      - feature/packer-customimages

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD_TEST }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME_TEST }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Tests
        env:
          DB_USERNAME_TEST: ${{ secrets.DB_USERNAME_TEST }}
          DB_PASSWORD_TEST: ${{ secrets.DB_PASSWORD_TEST }}
          DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
          DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
          DB_DIALECT_TEST: ${{ secrets.DB_DIALECT_TEST }}
        run: npm run test

  build-ami:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application artifact
        id: build
        run: |
          npm run zip

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build AMI with Packer
        run: |
          packer init ./packer
          packer build -var "artifact_path=/home/runner/work/webapp/webapp/webapp.zip" ./packer

