name: Packer Template Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build application artifact
        id: build
        run: |
          npm run zip

      - name: Run Packer init
        run: |
          packer init ./packer

      - name: Run Packer fmt
        id: packer-fmt
        run: |
          packer fmt -check=true ./packer

      - name: Run Packer validate
        id: packer-validate
        run: |
          packer validate -var "aws_region=${{ secrets.AWS_REGION }}" -var "ami_source=ami-04b4f1a9cf54c11d0" -var "ami_instance=t2.micro" -var "ami_prefix=webapp-aws-ubuntu-nodejs" -var "ami_users=${{ secrets.AMI_USERS }}" -var "artifact_path=/home/runner/work/webapp/webapp/webapp.zip" ./packer

