name: API Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      DB_USER: ${{ secrets.DB_USERNAME_TEST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD_TEST }}
      DB_DATABASE: ${{ vars.DB_NAME_TEST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Create MySQL Database
        run: mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD


      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Tests
        run: npm run test